### PR TITLE
updates Localytics to 3.8

### PR DESCRIPTION
**Pull request by ladanazita**
@f2prateek a user is experiencing some issues that were corrected in the more recent version of Localytics SDK:
http://docs.localytics.com/dev/sdk-changelog.html#sdk-changelog

### CODE REVIEW

**Comment by f2prateek** [comment]
Forgot to run `make install`.

**Comment by ladanazita** [comment]
whoops!  😊 
@f2prateek

**Comment by f2prateek** [comment]
lgtm

**Comment by f2prateek** [comment]
btw we don't need to update each time. Users can declared `pid 'Localytics', '~> 3.8'` and it will pick it up automatically.

**Pull request merged**
